[[constraint]]
  name = "github.com/uniplaces/logrus"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
